name: BoardGame
main: boardgame.Tahu.main.BoardGame
version: 0.5.0

commands:
  bggame:
    description: boardgame game
  bgg:
    description: boardgame game
  bgrole:
    description: boardgame role
  bgr:
    description: boardgame role